### PR TITLE
561+562 export to CSV with streaming

### PR DESCRIPTION
**Pull request by rui-castro**
Issues #561 and #562 

## Streaming results in CSV
Refactored `IndexResource` methods to use streaming for results in CSV.
Replaced methods `Browser#findCSV` and `BrowserHelper#findCSV` by `...#findAll`.
Added method `IndexService` `IterableIndexResult<T> findAll(final Class<T> returnClass, final Filter filter, final Sorter sorter, final Sublist sublist, final User user, final boolean justActive, final boolean removeDuplicates)`
Removed `SolrUtils#findCSV` method. `IterableIndexResult` is used instead.

## New parameters `exportFacets` and `filename`

Added 2 new attributes to `FindRequest`: `FindRequest#exportFacets` and `FindRequest#filename`.
Updated client calls to use these new parameters.

### CODE REVIEW

**Comment by luis100** [comment]
Why String[] and not List<String> in toCSVHeader() and other similar
methods? GWT now supports generics!

Em 03/10/2016 1:09 da manhã, "Rui Castro" <notifications@github.com>
escreveu:

**Comment by rui-castro** [comment]
@luis100 For no special reason. An array is enough.
Do you me to change it to List?

**Comment by luis100** [comment]
I guess it would be cleaner.

**Comment by rui-castro** [comment]
@luis100 done

**Comment by luis100** [comment]
merged into lf_dev

**Pull request closed without merging**
