### PR TITLE
#413 - Implemented new login error message for inactive users

### PR DESCRIPTION
**Pull request by rui-castro**
Issue #413

### CODE REVIEW

**Comment by luis100** [comment]
When SMTP is not configured and user is deativated, wrong message appears about email not verified.

**Comment by rui-castro** [comment]
@luis100 I think is fixed now.

* User registered and didn't verify the email yet, on login atempt will see a message "You must validate your email to login."
* User with email verified but inactive, on login atempt will see message "Wrong username or password", as it was before.

**Comment by rui-castro** [comment]
@luis100 ping

**Comment by luis100** [comment]
Merged into branch lf_dev

**Pull request closed without merging**
