### PR TITLE
319 - Implemented CSV output for IndexResource

### PR DESCRIPTION
**Pull request by rui-castro**
Issue #319
To produce CSV in `/index` requests, simply use header 
`Accepts: text/csv`

### CODE REVIEW

**Comment by hsilva-keep** [comment]
@rui-castro 
Why have you added another library for manipulating csv, as commons-csv from Apache is already a project dependency? Any good reason? Any strong limitation?

**Comment by rui-castro** [comment]
@hsilva-keep I didn't know we already had a CSV library. I'll review this.

**Comment by rui-castro** [comment]
@hsilva-keep @luis100 done

**Comment by rui-castro** [comment]
@luis100 @hsilva-keep support for facet data complete

### Results in CSV
#### Request
```
GET http://127.0.0.1:8888/api/v1/index?
  returnClass=org.roda.core.data.v2.user.RODAMember
```
#### Response
```csv
id,isActive,isUser,name,fullName,email,groups
rui,true,true,rui,Rui,rui.castro@gmail.com,[users]
guest,true,true,guest,Guest,demo-guest@roda-community.org,[guests]
producers,true,false,producers,Producers,,
users,true,false,users,Users,,
archivists,true,false,archivists,Archivists,,
administrators,true,false,administrators,Administrators,,
guests,true,false,guests,Guests,,
admin,true,true,admin,Administrator,demo-admin@roda-community.org,"[guests, archivists, administrators]"
```

### Facets in CSV
#### Request
```
GET http://127.0.0.1:8888/api/v1/index?
  returnClass=org.roda.core.data.v2.user.RODAMember&
  facet=isUser&
  facet=isActive
```
#### Response
```csv
field,label,value,count
isUser,false,false,5
isUser,true,true,3
isActive,true,true,8
```

**Comment by luis100** [comment]
integrated into lf_dev

**Pull request closed without merging**
